server:
  port: 8202

spring:
  application:
    name: surveillance-upms-biz
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}:8001
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
  datasource:
    dynamic:
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: SurveillanceHikariCP
      primary: base
      datasource:
        base:
          username: root
          password: password
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/video_surveillance?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:10086/surveillance/auth/user
