server:
  port: 10086

spring:
  application:
    name: surveillance-gateway
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: chuoyue
        password: password
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url}:8001
    gateway:
      routes:
        - id: surveillance-auth
          uri: lb://surveillance-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: surveillance-upms-api
          uri: lb://surveillance-upms-api
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: surveillance-upms-biz
          uri: lb://surveillance-upms-biz
          predicates:
            - Path=/biz/**
          filters:
            - StripPrefix=1






management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS