server:
  port: 8401

spring:
  application:
    name: surveillance-monitor-admin
  boot:
    admin:
      ui:
        title: ${spring.application.name}
  security:
    user:
      name: chuoyue
      password: password
