global:
  smtp_smarthost: 'smtp.126.com:465'
  smtp_from: 'fuyunwang@126.com'
  smtp_auth_username: 'fuyunwang'
  smtp_auth_password: 'password'
  smtp_require_tls: false

#templates:
#  - '/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 5m
  receiver: 'default-receiver'

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: '2375872953@qq.com'
        send_resolved: true