server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fuyunwang/video_surveillance_config
          search-paths: respo
          username:
          password:
          force-pull: true
          ignore-local-ssh-settings: true
      label: master
  application:
    name: surveillance-configs